name: Latest blog 
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  medium:
    name: Latest blog 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "MEDUIM-BLOG-LIST "
          feed_list: 'https://medium.com/@setoh1l/array-methods-1fb9ed7bacd2'
